language: python
# Need to keep up-to-date with the latest stable distribution:
# https://docs.travis-ci.com/user/reference/overview/
dist: xenial
cache: pip
# build matrix: different python and pandoc versions
python:
  # Exclude end-of-life branches
  # https://devguide.python.org/#branchstatus
  - "3.6"
  - "3.7"
  - "3.8" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
  #- "pypy3.5-6.0" # PyPy3 2.4.0 (CPython 3.2 compatible)
# https://groups.google.com/forum/?fromgroups#!topic/pandoc-discuss/uGASAhRydfI
env:
  #- pandocVersion=1.19.2.1 # Jan2017; disabled to reduce TravisCI time
  - pandocVersion=2.8.0.1
  - pandocVersion=latest
matrix:
    - python: "nightly"
  fast_finish: true
# download pandoc
before_install:
  - |
    if [[ $pandocVersion == "latest" ]]; then
      url="https://github.com/jgm/pandoc/releases/latest"
    else
      url="https://github.com/jgm/pandoc/releases/tag/$pandocVersion"
    fi
    path=$(curl -L $url | grep -o '/jgm/pandoc/releases/download/.*-amd64\.deb')
    downloadUrl="https://github.com$path"
    file=${path##*/}
# install dependencies
install:
  # pandoc
  - wget $downloadUrl &&
    sudo dpkg -i $file
  # latest pip dropped support for py3.2, which is the version of python in pypy3
  - if [[ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]]; then pip install -U pip; fi
  - pip install -e .[test]
before_script:
# commands to run tests
script:
  - py.test -vv --cov=panflute tests
  # put filters in $DATADIR for panflute's autofilter
  - mkdir -p $HOME/.pandoc/filters
  - find ./examples/panflute ./docs/source/_static -iname '*.py' -exec cp {} $HOME/.pandoc/filters/ \;
  # running all available .md files through panflute
  - find . -iname '*.md' -print0 | xargs -0 -i -n1 -P4 bash -c 'pandoc -t native -F panflute -o $0.native $0' {}
before_deploy:
  # create README.rst for PyPI README
  - pandoc -f markdown+autolink_bare_uris-fancy_lists-implicit_header_references -M date="`date "+%B %e, %Y"`" --toc -s -o README.rst README.md
  # debugging rst output
  ## install dependencies for rst to html
  - pip install -e .[pypi]
  ## test if the rst output is valid
  - rst2html.py README.rst > README.html
  # building wheels
  - python3 setup.py bdist_wheel
  ### prepare wheel
deploy:
  provider: pypi
  user: sergiocorreia
  password: $pypi_password
  # do not add bdist_wheel here, since it is done above
  distributions: "sdist"
  skip_cleanup: true
  on:
    branch: master
    python: "3.8"
    condition: $pandocVersion = latest
