name: Publish on PyPI

on:
  release:
    types: [published]
    # published, unpublished, created, edited, deleted, or prereleased

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install twine

      - name: Build source distribution
        run: |
          python3 setup.py sdist
          twine check dist/*

      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
        continue-on-error: false

      - name: Publish distribution to PyPI
        if: github.event.action == 'published' && !github.event.release.prerelease
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
